# Generated by Django 4.0.3 on 2024-12-03 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AddField(
            model_name="project",
            name="assigned_users",
            field=models.ManyToManyField(
                related_name="assigned_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
