# Generated by Django 4.0.3 on 2024-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
